/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Проверить состояние Research API
         * @description Проверяет доступность базы данных и сообщает время последнего снимка. При недоступной БД возвращает 503 с диагностическим телом вместо исключения.
         */
        get: operations["ResearchReadController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metric-fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Поля, допустимые в плейсхолдерах прозы вердикта
         * @description Отдаёт тот же перечень, по которому сервер отвергает неизвестный плейсхолдер. Сайт строит по нему панель вставки и подсветку опечаток; собственной копии списка у клиента быть не должно — она разойдётся на первом новом поле.
         */
        get: operations["ResearchMetricFieldsController_fields"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/preview/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Предварительно рассчитать метрики
         * @description Рассчитывает метрики и оценку по присланным значениям и опубликованной медиане сектора, не записывая протокол, снимок или оценку.
         */
        post: operations["ResearchWriteController_previewMetrics"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/protocols": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить опубликованные протоколы
         * @description Возвращает страницу опубликованных протоколов, при необходимости ограниченную сектором. includeDrafts=true с действующим x-api-key также включает неопубликованные протоколы. Пустая выборка возвращается пустым массивом.
         */
        get: operations["ResearchReadController_protocols"];
        put?: never;
        /**
         * Создать протокол
         * @description Создаёт паспорт протокола перед публикацией материалов. Повторный slug возвращает 409 и не изменяет существующий протокол.
         */
        post: operations["ResearchWriteController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/protocols/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить страницу протокола
         * @description Возвращает опубликованный паспорт и последние опубликованные материалы. Если slug не опубликован или не существует, возвращает 404.
         */
        get: operations["ResearchReadController_protocol"];
        /**
         * Обновить паспорт протокола
         * @description Изменяет только переданные мутабельные поля паспорта. Неизвестный slug не создаётся автоматически.
         */
        put: operations["ResearchWriteController_update"];
        post?: never;
        /**
         * Удалить протокол
         * @description Удаляет протокол и всю его research-историю каскадом без тела ответа.
         */
        delete: operations["ResearchWriteController_deleteProtocol"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/protocols/{slug}/methodology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Добавить версию методики
         * @description Создаёт следующую версию методики протокола. Конфликт естественного ключа возвращает 409.
         */
        post: operations["ResearchWriteController_methodology"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/protocols/{slug}/methodology/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Полностью заменить методику
         * @description Заменяет все поля существующей методики и позволяет сменить её номер версии. Неизвестный ключ возвращает 404, занятый новый номер — 409.
         */
        put: operations["ResearchWriteController_replaceMethodology"];
        post?: never;
        /**
         * Удалить методику
         * @description Удаляет методику по текущему номеру версии без тела ответа.
         */
        delete: operations["ResearchWriteController_deleteMethodology"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/protocols/{slug}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить снимки протокола
         * @description Возвращает страницу снимков опубликованного протокола от новых к старым. Если протокол не опубликован или не существует, возвращает 404.
         */
        get: operations["ResearchReadController_snapshots"];
        put?: never;
        /**
         * Добавить снимок и оценку
         * @description Атомарно сохраняет исходные значения снимка, рассчитывает метрики и оценку. Повторный момент замера возвращает 409.
         */
        post: operations["ResearchWriteController_snapshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/protocols/{slug}/snapshots/{takenAt}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Полностью заменить снимок
         * @description Заменяет все исходные поля снимка, позволяет сменить takenAt и пересчитывает связанную оценку. Неизвестный ключ возвращает 404, занятый новый takenAt — 409.
         */
        put: operations["ResearchWriteController_replaceSnapshot"];
        post?: never;
        /**
         * Удалить снимок
         * @description Удаляет снимок и его оценку каскадом без тела ответа.
         */
        delete: operations["ResearchWriteController_deleteSnapshot"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/protocols/{slug}/triggers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Заменить триггеры протокола
         * @description Атомарно заменяет мутабельный набор триггеров протокола переданным списком; пустой список удаляет все его триггеры.
         */
        put: operations["ResearchWriteController_triggers"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/protocols/{slug}/verdicts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить вердикты протокола
         * @description Возвращает всю опубликованную историю вердиктов протокола по версиям. Если протокол не опубликован или не существует, возвращает 404.
         */
        get: operations["ResearchReadController_verdicts"];
        put?: never;
        /**
         * Опубликовать вердикт
         * @description Создаёт следующую версию вердикта протокола. Конфликт естественного ключа возвращает 409.
         */
        post: operations["ResearchWriteController_verdict"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/protocols/{slug}/verdicts/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Полностью заменить вердикт
         * @description Заменяет все поля вердикта и позволяет сменить его версию. Неизвестный ключ возвращает 404, занятая новая версия — 409.
         */
        put: operations["ResearchWriteController_replaceVerdict"];
        post?: never;
        /**
         * Удалить вердикт
         * @description Удаляет вердикт без тела ответа; текущим автоматически становится следующий по убыванию версии.
         */
        delete: operations["ResearchWriteController_deleteVerdict"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/protocols/{slug}/verdicts/{version}/reasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Полностью заменить причины вердикта
         * @description Атомарно заменяет три структурированные ссылки на метрики; частичное слияние не выполняется.
         */
        put: operations["ResearchWriteController_replaceVerdictReasons"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/protocols/{slug}/verdicts/{version}/texts/{locale}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Полностью заменить локализованный текст вердикта
         * @description Создаёт или полностью заменяет текст указанной локали без изменения других переводов.
         */
        put: operations["ResearchWriteController_replaceVerdictText"];
        post?: never;
        /**
         * Удалить локализованный текст вердикта
         * @description Удаляет только указанную локаль и не изменяет сам вердикт или другие переводы.
         */
        delete: operations["ResearchWriteController_deleteVerdictText"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sectors/{sector}/table": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить сравнительную таблицу сектора
         * @description Возвращает последние опубликованные метрики и риск по протоколам сектора. Если данных нет, возвращает пустой массив.
         */
        get: operations["ResearchReadController_sectorTable"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/triggers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить активные публичные триггеры
         * @description Возвращает активные публичные условия пересмотра вердикта с необязательной фильтрацией по протоколу и тарифу бота.
         */
        get: operations["ResearchReadController_triggers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AppendMethodologyDto: {
            /** @description URL адаптера или источника расчёта; null означает отсутствие ссылки. */
            adapterUrl?: string | null;
            /** @description Описание политики выкупа токена; null означает, что политика не задана. */
            buybackPolicy?: string | null;
            /**
             * @description Определяет, показывается ли триггер через публичную read-ручку.
             * @default true
             */
            excludedAddresses: boolean;
            /** @description URL или описание источника структуры комиссий; null означает отсутствие источника. */
            feeStructureSource?: string | null;
            /** @description URL или описание источника токеновых стимулов; null означает отсутствие источника. */
            incentivesSource?: string | null;
            /** @description URL или описание источника reserve factor; null означает отсутствие источника. */
            reserveFactorSource?: string | null;
            /** @description Точное правило, по которому рассчитана выручка протокола за 12 месяцев. */
            revenueDefinition: string;
            /** @description Порог доли владения для крупного держателя в процентах, где 5 означает 5%; null — порог не задан. */
            whaleThresholdPct?: number | null;
        };
        AppendSnapshotDto: {
            /** @description Годовой объём выкупа токена в долларах; null — данных нет, 0 — измеренный ноль. */
            buybackAnnualUsd?: number | null;
            /** @description Циркулирующее предложение в токенах; null — данных нет, 0 — измеренный ноль. */
            circulatingSupply?: number | null;
            /** @description Эмиссия за 12 месяцев в токенах; null — данных нет, 0 — измеренный ноль. */
            emissions12mTokens?: number | null;
            /** @description Полностью разводнённая стоимость в долларах; null — данных нет, 0 — измеренный ноль. */
            fdv?: number | null;
            /** @description Рыночная капитализация циркулирующего предложения в долларах; null — данных нет, 0 — измеренный ноль. */
            marketCap?: number | null;
            /** @description Цена одного токена в долларах; null — данных нет, 0 — измеренный ноль. */
            price?: number | null;
            /** @description Выручка протокола за 12 месяцев в долларах; null — данных нет, 0 — измеренный ноль. */
            protocolRevenue12m?: number | null;
            /** @description Структурированные ошибки источников; null означает, что ошибок не зафиксировано. */
            sourceErrors?: {
                [key: string]: unknown;
            } | null;
            /**
             * @description Полнота исходных данных: OK, PARTIAL или FAILED.
             * @default OK
             * @enum {string}
             */
            sourceStatus: "OK" | "PARTIAL" | "FAILED";
            /**
             * Format: date-time
             * @description UTC-время, к которому относятся измеренные значения снимка.
             */
            takenAt: string;
            /** @description Токеновые стимулы за 12 месяцев в долларах; null — данных нет, 0 — измеренный ноль. */
            tokenIncentives12m?: number | null;
            /** @description Полное предложение в токенах; null — данных нет, 0 — измеренный ноль. */
            totalSupply?: number | null;
            /** @description Разблокировки за 12 месяцев в токенах; null — данных нет, 0 — измеренный ноль. */
            unlocks12mTokens?: number | null;
        };
        AppendVerdictDto: {
            /** @description Причина изменения относительно прошлого вердикта; null допустим для первого вердикта. */
            changeReason?: string | null;
            /** @description Причины и локализованные тексты, записываемые той же транзакцией. Обязательны при isPublished = true; null допустим только для черновика. */
            content?: components["schemas"]["VerdictContentDto"] | null;
            /**
             * @description Признак публикации вердикта; false сохраняет доступный только по ключу черновик.
             * @default false
             */
            isPublished: boolean;
            /** @description Список сработавших блокирующих условий риска; пустой массив означает, что ни одно не сработало. */
            killersFired: ("NEGATIVE_NET_REVENUE" | "NEGATIVE_FLOW_WITH_UNLOCKS" | "NO_VALUE_ACCRUAL" | "UNVERIFIABLE_REVENUE" | "UNILATERAL_TEAM_CONTROL" | "UNRESOLVED_SECURITY_ISSUE" | "INSUFFICIENT_LIQUIDITY" | "HOLDER_CONCENTRATION" | "MISSING_CRITICAL_DATA")[];
            /**
             * Format: date-time
             * @description UTC-время, с которого вердикт считается опубликованным.
             */
            publishedAt: string;
            /**
             * @deprecated
             * @description Устаревшее свободное обоснование. Настоящие причины — в content.reasons; поле остаётся обязательным до миграции переноса и заполняется пустым объектом.
             */
            reasons: {
                [key: string]: unknown;
            };
            /**
             * @description Итоговый уровень риска: LOW, MEDIUM или HIGH; null в таблице означает отсутствие вердикта.
             * @enum {string}
             */
            riskLabel: "LOW" | "MEDIUM" | "HIGH";
            /**
             * Format: date-time
             * @description UTC-время опорного снимка как внешний естественный ключ; null означает отсутствие опорного снимка.
             */
            snapshotTakenAt?: string | null;
        };
        CreateProtocolDto: {
            /**
             * @description Идентификаторы сетей, в которых развёрнут протокол; пустой массив означает, что сети не указаны.
             * @example [
             *       "ethereum"
             *     ]
             */
            chains: string[];
            /** @description Идентификатор актива в CoinGecko; null означает, что источник не связан. */
            coingeckoId?: string | null;
            /**
             * @description Адреса и метаданные контрактов по сетям в JSON-объекте.
             * @example {
             *       "ethereum": "0x..."
             *     }
             */
            contracts: {
                [key: string]: unknown;
            };
            /** @description Идентификатор протокола в DefiLlama; null означает, что источник не связан. */
            defillamaSlug?: string | null;
            /**
             * @description Определяет видимость протокола в публичных read-ручках.
             * @default false
             */
            isPublished: boolean;
            /**
             * @description Отображаемое название протокола для таблиц и страницы разбора.
             * @example Aave
             */
            name: string;
            /**
             * @description Сектор бизнес-модели протокола: LENDING или PERPS.
             * @enum {string}
             */
            sector: "LENDING" | "PERPS";
            /**
             * @description Стабильный идентификатор протокола в нижнем регистре с дефисами.
             * @example aave
             */
            slug: string;
            /**
             * @description Биржевой тикер токена без знака валюты.
             * @example AAVE
             */
            ticker: string;
        };
        PreviewMetricsDto: {
            /** @description Годовой объём выкупа токена в долларах; null — данных нет, 0 — измеренный ноль. */
            buybackAnnualUsd?: number | null;
            /** @description Циркулирующее предложение в токенах; null — данных нет, 0 — измеренный ноль. */
            circulatingSupply?: number | null;
            /** @description Эмиссия за 12 месяцев в токенах; null — данных нет, 0 — измеренный ноль. */
            emissions12mTokens?: number | null;
            /** @description Полностью разводнённая стоимость в долларах; null — данных нет, 0 — измеренный ноль. */
            fdv?: number | null;
            /** @description Рыночная капитализация циркулирующего предложения в долларах; null — данных нет, 0 — измеренный ноль. */
            marketCap?: number | null;
            /** @description Цена одного токена в долларах; null — данных нет, 0 — измеренный ноль. */
            price?: number | null;
            /** @description Выручка протокола за 12 месяцев в долларах; null — данных нет, 0 — измеренный ноль. */
            protocolRevenue12m?: number | null;
            /**
             * @description Сектор бизнес-модели протокола: LENDING или PERPS.
             * @enum {string}
             */
            sector: "LENDING" | "PERPS";
            /** @description Структурированные ошибки источников; null означает, что ошибок не зафиксировано. */
            sourceErrors?: {
                [key: string]: unknown;
            } | null;
            /**
             * @description Полнота исходных данных: OK, PARTIAL или FAILED.
             * @default OK
             * @enum {string}
             */
            sourceStatus: "OK" | "PARTIAL" | "FAILED";
            /**
             * Format: date-time
             * @description UTC-время, к которому относятся измеренные значения снимка.
             */
            takenAt: string;
            /** @description Токеновые стимулы за 12 месяцев в долларах; null — данных нет, 0 — измеренный ноль. */
            tokenIncentives12m?: number | null;
            /** @description Полное предложение в токенах; null — данных нет, 0 — измеренный ноль. */
            totalSupply?: number | null;
            /** @description Разблокировки за 12 месяцев в токенах; null — данных нет, 0 — измеренный ноль. */
            unlocks12mTokens?: number | null;
        };
        ReplaceMethodologyDto: {
            /** @description URL адаптера или источника расчёта; null означает отсутствие ссылки. */
            adapterUrl?: string | null;
            /** @description Описание политики выкупа токена; null означает, что политика не задана. */
            buybackPolicy?: string | null;
            /**
             * @description Определяет, показывается ли триггер через публичную read-ручку.
             * @default true
             */
            excludedAddresses: boolean;
            /** @description URL или описание источника структуры комиссий; null означает отсутствие источника. */
            feeStructureSource?: string | null;
            /** @description URL или описание источника токеновых стимулов; null означает отсутствие источника. */
            incentivesSource?: string | null;
            /** @description URL или описание источника reserve factor; null означает отсутствие источника. */
            reserveFactorSource?: string | null;
            /** @description Точное правило, по которому рассчитана выручка протокола за 12 месяцев. */
            revenueDefinition: string;
            /** @description Новый натуральный номер версии методики; занятый номер возвращает 409. */
            version: number;
            /** @description Порог доли владения для крупного держателя в процентах, где 5 означает 5%; null — порог не задан. */
            whaleThresholdPct?: number | null;
        };
        ReplaceSnapshotDto: {
            /** @description Годовой объём выкупа токена в долларах; null — данных нет, 0 — измеренный ноль. */
            buybackAnnualUsd?: number | null;
            /** @description Циркулирующее предложение в токенах; null — данных нет, 0 — измеренный ноль. */
            circulatingSupply?: number | null;
            /** @description Эмиссия за 12 месяцев в токенах; null — данных нет, 0 — измеренный ноль. */
            emissions12mTokens?: number | null;
            /** @description Полностью разводнённая стоимость в долларах; null — данных нет, 0 — измеренный ноль. */
            fdv?: number | null;
            /** @description Рыночная капитализация циркулирующего предложения в долларах; null — данных нет, 0 — измеренный ноль. */
            marketCap?: number | null;
            /** @description Цена одного токена в долларах; null — данных нет, 0 — измеренный ноль. */
            price?: number | null;
            /** @description Выручка протокола за 12 месяцев в долларах; null — данных нет, 0 — измеренный ноль. */
            protocolRevenue12m?: number | null;
            /** @description Структурированные ошибки источников; null означает, что ошибок не зафиксировано. */
            sourceErrors?: {
                [key: string]: unknown;
            } | null;
            /**
             * @description Полнота исходных данных: OK, PARTIAL или FAILED.
             * @default OK
             * @enum {string}
             */
            sourceStatus: "OK" | "PARTIAL" | "FAILED";
            /**
             * Format: date-time
             * @description UTC-время, к которому относятся измеренные значения снимка.
             */
            takenAt: string;
            /** @description Токеновые стимулы за 12 месяцев в долларах; null — данных нет, 0 — измеренный ноль. */
            tokenIncentives12m?: number | null;
            /** @description Полное предложение в токенах; null — данных нет, 0 — измеренный ноль. */
            totalSupply?: number | null;
            /** @description Разблокировки за 12 месяцев в токенах; null — данных нет, 0 — измеренный ноль. */
            unlocks12mTokens?: number | null;
        };
        ReplaceTriggerDto: {
            /**
             * @description Минимальный тариф бота, которому доступен триггер: FREE или PAID.
             * @default FREE
             * @enum {string}
             */
            botTier: "FREE" | "PAID";
            /**
             * @description Определяет, участвует ли триггер в текущем наборе условий.
             * @default true
             */
            isActive: boolean;
            /**
             * @description Определяет, показывается ли триггер через публичную read-ручку.
             * @default true
             */
            isPublic: boolean;
            /**
             * @description Метрика, изменение которой проверяет триггер.
             * @enum {string}
             */
            metric: "PRICE" | "PROTOCOL_REVENUE_12M" | "NET_REVENUE_12M" | "FDV_REVENUE" | "VAR_PCT" | "SPR_PCT" | "NET_TOKEN_FLOW_PCT" | "FLOW_NEUTRAL_PRICE" | "PREMIUM_PCT";
            /**
             * @description Оператор сравнения метрики с порогом, включая пересечение вверх или вниз.
             * @enum {string}
             */
            operator: "GTE" | "LTE" | "CROSSES_ABOVE" | "CROSSES_BELOW";
            /** @description Порог в единицах выбранной метрики: доллары для PRICE и FLOW_NEUTRAL_PRICE, проценты для *_PCT, множитель для FDV_REVENUE. */
            threshold: number;
            /** @description Текст ожидаемого влияния срабатывания триггера на пересмотр вердикта. */
            verdictEffect: string;
        };
        ReplaceTriggersDto: {
            /** @description Активные публичные условия, при которых требуется пересмотреть вердикт. */
            triggers: components["schemas"]["ReplaceTriggerDto"][];
        };
        ReplaceVerdictDto: {
            /** @description Причина изменения относительно прошлого вердикта; null допустим для первого вердикта. */
            changeReason?: string | null;
            /** @description Причины и локализованные тексты, записываемые той же транзакцией. Обязательны при isPublished = true; null допустим только для черновика. */
            content?: components["schemas"]["VerdictContentDto"] | null;
            /**
             * @description Признак публикации вердикта; false сохраняет доступный только по ключу черновик.
             * @default false
             */
            isPublished: boolean;
            /** @description Список сработавших блокирующих условий риска; пустой массив означает, что ни одно не сработало. */
            killersFired: ("NEGATIVE_NET_REVENUE" | "NEGATIVE_FLOW_WITH_UNLOCKS" | "NO_VALUE_ACCRUAL" | "UNVERIFIABLE_REVENUE" | "UNILATERAL_TEAM_CONTROL" | "UNRESOLVED_SECURITY_ISSUE" | "INSUFFICIENT_LIQUIDITY" | "HOLDER_CONCENTRATION" | "MISSING_CRITICAL_DATA")[];
            /**
             * Format: date-time
             * @description UTC-время, с которого вердикт считается опубликованным.
             */
            publishedAt: string;
            /**
             * @deprecated
             * @description Устаревшее свободное обоснование. Настоящие причины — в content.reasons; поле остаётся обязательным до миграции переноса и заполняется пустым объектом.
             */
            reasons: {
                [key: string]: unknown;
            };
            /**
             * @description Итоговый уровень риска: LOW, MEDIUM или HIGH; null в таблице означает отсутствие вердикта.
             * @enum {string}
             */
            riskLabel: "LOW" | "MEDIUM" | "HIGH";
            /**
             * Format: date-time
             * @description UTC-время опорного снимка как внешний естественный ключ; null означает отсутствие опорного снимка.
             */
            snapshotTakenAt?: string | null;
            /**
             * @description Новый натуральный номер версии вердикта в формате major.minor; занятая версия возвращает 409.
             * @example 1.1
             */
            version: string;
        };
        ReplaceVerdictReasonDto: {
            /**
             * @description Метрика снимка или оценки, подтверждающая причину.
             * @enum {string}
             */
            metricRef: "PRICE" | "CIRCULATING_SUPPLY" | "TOTAL_SUPPLY" | "MARKET_CAP" | "FDV" | "PROTOCOL_REVENUE_12M" | "TOKEN_INCENTIVES_12M" | "NET_REVENUE_12M" | "FDV_REVENUE" | "BUYBACK_ANNUAL_USD" | "VAR_PCT" | "EMISSIONS_12M_TOKENS" | "UNLOCKS_12M_TOKENS" | "SPR_PCT" | "NET_TOKEN_FLOW_PCT" | "SECTOR_MEDIAN_FDV_REVENUE" | "FAIR_FDV" | "PREMIUM_PCT" | "FLOW_NEUTRAL_PRICE" | "IMPLIED_REVENUE" | "IMPLIED_GROWTH_X";
            /** @description Позиция причины в тексте: 1, 2 или 3. */
            position: number;
        };
        ReplaceVerdictReasonsDto: {
            /** @description Три упорядоченные ссылки на разные метрики. */
            reasons: components["schemas"]["ReplaceVerdictReasonDto"][];
        };
        ReplaceVerdictTextDto: {
            /** @description Markdown-текст разбора с валидными плейсхолдерами метрик. */
            body: string;
            /** @description Краткое описание изменения перевода; null, если его нет. */
            changeSummary?: string | null;
            /** @description Непустой Markdown-блок контраргументов. */
            counterarguments: string;
            /**
             * @description Признак машинного перевода текста.
             * @default false
             */
            isMachineTranslated: boolean;
            /** @description Три локализованных текста причин в порядке позиций 1–3. */
            reasonTexts: string[];
        };
        ResearchFreshnessDeviationDto: {
            /** @description Значение метрики в опорном снимке. */
            baseline: number;
            /** @description Значение метрики в последнем снимке. */
            current: number;
            /** @description Знаковое отклонение: проценты для относительных порогов или процентные пункты для потоков. */
            delta: number;
            /**
             * @description Метрика, по которой превышен порог свежести.
             * @enum {string}
             */
            metricRef: "PROTOCOL_REVENUE_12M" | "NET_TOKEN_FLOW_PCT" | "SPR_PCT" | "FDV_REVENUE" | "PRICE";
            /** @description Порог в тех же единицах, что delta; элемент появляется только при его превышении. */
            threshold: number;
        };
        ResearchFreshnessResponseDto: {
            /**
             * Format: date-time
             * @description UTC-время опорного снимка; null означает, что опора вердикта отсутствует или удалена.
             */
            baselineTakenAt: string | null;
            /** @description Метрики, отклонение которых строго превысило доменный порог. */
            deviations: components["schemas"]["ResearchFreshnessDeviationDto"][];
            /**
             * @description Вычисленное сервером состояние свежести страницы.
             * @enum {string}
             */
            status: "CURRENT" | "DATA_CHANGED" | "VERDICT_REVISED" | "DATA_UNVERIFIED";
        };
        ResearchHealthResponseDto: {
            /**
             * @description Состояние соединения с PostgreSQL: ok или down.
             * @enum {string}
             */
            db: "ok" | "down";
            /**
             * Format: date-time
             * @description UTC-время последнего сохранённого снимка; null означает, что снимков ещё нет.
             */
            latestSnapshotAt: string | null;
            /**
             * @description Сводное состояние API: ok при доступной БД, иначе degraded.
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** @description Версия развёрнутого Research API. */
            version: string;
        };
        ResearchMethodologyResponseDto: {
            /** @description URL адаптера или источника расчёта; null означает отсутствие ссылки. */
            adapterUrl: string | null;
            /** @description Описание политики выкупа токена; null означает, что политика не задана. */
            buybackPolicy: string | null;
            /**
             * Format: date-time
             * @description UTC-время создания записи, назначенное сервером.
             */
            createdAt: string;
            /** @description Служебные адреса, исключённые из расчёта концентрации; null означает, что список не задан. */
            excludedAddresses: string[] | null;
            /** @description URL или описание источника структуры комиссий; null означает отсутствие источника. */
            feeStructureSource: string | null;
            /** @description URL или описание источника токеновых стимулов; null означает отсутствие источника. */
            incentivesSource: string | null;
            /** @description URL или описание источника reserve factor; null означает отсутствие источника. */
            reserveFactorSource: string | null;
            /** @description Точное правило, по которому рассчитана выручка протокола за 12 месяцев. */
            revenueDefinition: string;
            /**
             * Format: date-time
             * @description UTC-время последней правки методики, назначенное сервером.
             */
            updatedAt: string;
            /** @description Натуральный номер редакции методики; больший номер — более поздняя редакция. Номер задаётся при записи и может быть изменён полной заменой. */
            version: number;
            /** @description Порог доли владения для крупного держателя в процентах, где 5 означает 5%; null — порог не задан. */
            whaleThresholdPct: number | null;
        };
        ResearchMetricFieldDto: {
            /** @description Имя поля внутри источника в ответе страницы протокола. */
            field: string;
            /** @description Значение ResearchMetricRef, на которое ссылается структурированная причина вердикта. */
            metricRef: string;
            /** @description Строка плейсхолдера без фигурных скобок; в прозе пишется как {{placeholder}}. */
            placeholder: string;
            /**
             * @description Откуда берётся значение: snapshot — измеренные числа среза, valuation — расчётные уровни оценки.
             * @enum {string}
             */
            source: "snapshot" | "valuation";
        };
        ResearchPreviewMetricsDto: {
            /** @description Отношение FDV к годовой выручке, выраженное множителем; null — расчёт невозможен. */
            fdvRevenue: number | null;
            /** @description Выручка за 12 месяцев минус токеновые стимулы, в долларах; null — расчёт невозможен, 0 — измеренный ноль. */
            netRevenue12m: number | null;
            /** @description Чистый годовой поток токена относительно циркулирующего предложения в процентах; null — расчёт невозможен. */
            netTokenFlowPct: number | null;
            /** @description Выручка протокола за 12 месяцев в долларах; null — данных нет, 0 — измеренный ноль. */
            protocolRevenue12m: number | null;
            /** @description Supply Pressure Ratio в процентах; null — расчёт невозможен, 0 — измеренный ноль. */
            sprPct: number | null;
            /** @description Value Accrual Ratio в процентах; null — расчёт невозможен, 0 — измеренный ноль. */
            varPct: number | null;
        };
        ResearchPreviewResponseDto: {
            /** @description Шесть производных метрик, рассчитанных без записи данных. */
            metrics: components["schemas"]["ResearchPreviewMetricsDto"];
            /** @description Три уровня оценки и размер секторной выборки; null у отдельных уровней означает невозможность расчёта. */
            valuation: components["schemas"]["ResearchPreviewValuationDto"];
        };
        ResearchPreviewValuationDto: {
            /** @description Расчётная справедливая полностью разводнённая стоимость в долларах; null — расчёт невозможен. */
            fairFdv: number | null;
            /** @description Цена токена в долларах, при которой чистый токеновый поток равен нулю; null — расчёт невозможен. */
            flowNeutralPrice: number | null;
            /** @description Отношение подразумеваемой выручки к измеренной, выраженное множителем; null — расчёт невозможен. */
            impliedGrowthX: number | null;
            /** @description Годовая выручка в долларах, подразумеваемая текущим FDV и медианой сектора; null — расчёт невозможен. */
            impliedRevenue: number | null;
            /** @description Отклонение текущего FDV от справедливого FDV в процентах; null — расчёт невозможен. */
            premiumPct: number | null;
            /** @description Медианное отношение FDV к годовой выручке среди опубликованных протоколов сектора; null — выборки недостаточно. */
            sectorMedianFdvRevenue: number | null;
            /** @description Число опубликованных протоколов с пригодным FDV/Revenue, вошедших в медиану сектора. */
            sectorSampleSize: number;
        };
        ResearchProtocolListItemDto: {
            /** @description Идентификаторы сетей, в которых развёрнут протокол; пустой массив означает, что сети не указаны. */
            chains: string[];
            /** @description Отображаемое название протокола для таблиц и страницы разбора. */
            name: string;
            /**
             * @description Сектор бизнес-модели протокола: LENDING или PERPS.
             * @enum {string}
             */
            sector: "LENDING" | "PERPS";
            /** @description Стабильный идентификатор протокола в нижнем регистре с дефисами. */
            slug: string;
            /**
             * Format: date-time
             * @description UTC-время, к которому относятся измеренные значения снимка.
             */
            takenAt: string | null;
            /** @description Биржевой тикер токена без знака валюты. */
            ticker: string;
        };
        ResearchProtocolPageDto: {
            /** @description Свежесть вердикта относительно опорного и последнего снимков, включая только превышения доменных порогов. */
            freshness: components["schemas"]["ResearchFreshnessResponseDto"];
            /** @description Последняя опубликованная методика; null означает, что методика ещё не опубликована. */
            methodology: components["schemas"]["ResearchMethodologyResponseDto"] | null;
            /** @description Опубликованный паспорт протокола. */
            protocol: components["schemas"]["ResearchProtocolResponseDto"];
            /** @description Последний опубликованный снимок с оценкой; null означает, что снимков ещё нет. */
            snapshot: components["schemas"]["ResearchSnapshotResponseDto"] | null;
            /** @description Активные публичные условия, при которых требуется пересмотреть вердикт. */
            triggers: components["schemas"]["ResearchTriggerResponseDto"][];
            /** @description Последний опубликованный вердикт; null означает, что вердиктов ещё нет. */
            verdict: components["schemas"]["ResearchVerdictResponseDto"] | null;
        };
        ResearchProtocolResponseDto: {
            /** @description Идентификаторы сетей, в которых развёрнут протокол; пустой массив означает, что сети не указаны. */
            chains: string[];
            /** @description Идентификатор актива в CoinGecko; null означает, что источник не связан. */
            coingeckoId: string | null;
            /** @description Адреса и метаданные контрактов по сетям в JSON-объекте. */
            contracts: {
                [key: string]: unknown;
            };
            /**
             * Format: date-time
             * @description UTC-время создания записи, назначенное сервером.
             */
            createdAt: string;
            /** @description Идентификатор протокола в DefiLlama; null означает, что источник не связан. */
            defillamaSlug: string | null;
            /** @description Определяет видимость протокола в публичных read-ручках. */
            isPublished: boolean;
            /** @description Отображаемое название протокола для таблиц и страницы разбора. */
            name: string;
            /**
             * @description Сектор бизнес-модели протокола: LENDING или PERPS.
             * @enum {string}
             */
            sector: "LENDING" | "PERPS";
            /** @description Стабильный идентификатор протокола в нижнем регистре с дефисами. */
            slug: string;
            /** @description Биржевой тикер токена без знака валюты. */
            ticker: string;
            /**
             * Format: date-time
             * @description UTC-время последнего изменения мутабельной записи, назначенное сервером.
             */
            updatedAt: string;
        };
        ResearchSectorTableRowDto: {
            /** @description Отношение FDV к годовой выручке, выраженное множителем; null — расчёт невозможен. */
            fdvRevenue: number | null;
            /** @description Отображаемое название протокола для таблиц и страницы разбора. */
            name: string;
            /** @description Выручка за 12 месяцев минус токеновые стимулы, в долларах; null — расчёт невозможен, 0 — измеренный ноль. */
            netRevenue12m: number | null;
            /** @description Чистый годовой поток токена относительно циркулирующего предложения в процентах; null — расчёт невозможен. */
            netTokenFlowPct: number | null;
            /** @description Выручка протокола за 12 месяцев в долларах; null — данных нет, 0 — измеренный ноль. */
            protocolRevenue12m: number | null;
            /**
             * @description Итоговый уровень риска: LOW, MEDIUM или HIGH; null в таблице означает отсутствие вердикта.
             * @enum {string|null}
             */
            riskLabel: "LOW" | "MEDIUM" | "HIGH" | null;
            /**
             * @description Сектор бизнес-модели протокола: LENDING или PERPS.
             * @enum {string}
             */
            sector: "LENDING" | "PERPS";
            /** @description Стабильный идентификатор протокола в нижнем регистре с дефисами. */
            slug: string;
            /** @description Supply Pressure Ratio в процентах; null — расчёт невозможен, 0 — измеренный ноль. */
            sprPct: number | null;
            /**
             * Format: date-time
             * @description UTC-время, к которому относятся измеренные значения снимка.
             */
            takenAt: string | null;
            /** @description Биржевой тикер токена без знака валюты. */
            ticker: string;
            /** @description Value Accrual Ratio в процентах; null — расчёт невозможен, 0 — измеренный ноль. */
            varPct: number | null;
        };
        ResearchSnapshotResponseDto: {
            /** @description Годовой объём выкупа токена в долларах; null — данных нет, 0 — измеренный ноль. */
            buybackAnnualUsd: number | null;
            /** @description Циркулирующее предложение в токенах; null — данных нет, 0 — измеренный ноль. */
            circulatingSupply: number | null;
            /**
             * Format: date-time
             * @description UTC-время создания записи, назначенное сервером.
             */
            createdAt: string;
            /** @description Эмиссия за 12 месяцев в токенах; null — данных нет, 0 — измеренный ноль. */
            emissions12mTokens: number | null;
            /** @description Полностью разводнённая стоимость в долларах; null — данных нет, 0 — измеренный ноль. */
            fdv: number | null;
            /** @description Отношение FDV к годовой выручке, выраженное множителем; null — расчёт невозможен. */
            fdvRevenue: number | null;
            /** @description Рыночная капитализация циркулирующего предложения в долларах; null — данных нет, 0 — измеренный ноль. */
            marketCap: number | null;
            /** @description Выручка за 12 месяцев минус токеновые стимулы, в долларах; null — расчёт невозможен, 0 — измеренный ноль. */
            netRevenue12m: number | null;
            /** @description Чистый годовой поток токена относительно циркулирующего предложения в процентах; null — расчёт невозможен. */
            netTokenFlowPct: number | null;
            /** @description Цена одного токена в долларах; null — данных нет, 0 — измеренный ноль. */
            price: number | null;
            /** @description Выручка протокола за 12 месяцев в долларах; null — данных нет, 0 — измеренный ноль. */
            protocolRevenue12m: number | null;
            /** @description Структурированные ошибки источников; null означает, что ошибок не зафиксировано. */
            sourceErrors: {
                [key: string]: unknown;
            } | null;
            /**
             * @description Полнота исходных данных: OK, PARTIAL или FAILED.
             * @enum {string}
             */
            sourceStatus: "OK" | "PARTIAL" | "FAILED";
            /** @description Supply Pressure Ratio в процентах; null — расчёт невозможен, 0 — измеренный ноль. */
            sprPct: number | null;
            /**
             * Format: date-time
             * @description UTC-время, к которому относятся измеренные значения снимка.
             */
            takenAt: string;
            /** @description Токеновые стимулы за 12 месяцев в долларах; null — данных нет, 0 — измеренный ноль. */
            tokenIncentives12m: number | null;
            /** @description Полное предложение в токенах; null — данных нет, 0 — измеренный ноль. */
            totalSupply: number | null;
            /** @description Разблокировки за 12 месяцев в токенах; null — данных нет, 0 — измеренный ноль. */
            unlocks12mTokens: number | null;
            /**
             * Format: date-time
             * @description UTC-время последней правки снимка, назначенное сервером.
             */
            updatedAt: string;
            /** @description Три уровня оценки и размер секторной выборки; null у отдельных уровней означает невозможность расчёта. */
            valuation: components["schemas"]["ResearchValuationResponseDto"] | null;
            /** @description Value Accrual Ratio в процентах; null — расчёт невозможен, 0 — измеренный ноль. */
            varPct: number | null;
        };
        ResearchTriggerResponseDto: {
            /**
             * @description Минимальный тариф бота, которому доступен триггер: FREE или PAID.
             * @enum {string}
             */
            botTier: "FREE" | "PAID";
            /**
             * Format: date-time
             * @description UTC-время создания записи, назначенное сервером.
             */
            createdAt: string;
            /** @description Определяет, участвует ли триггер в текущем наборе условий. */
            isActive: boolean;
            /** @description Определяет, показывается ли триггер через публичную read-ручку. */
            isPublic: boolean;
            /**
             * @description Метрика, изменение которой проверяет триггер.
             * @enum {string}
             */
            metric: "PRICE" | "PROTOCOL_REVENUE_12M" | "NET_REVENUE_12M" | "FDV_REVENUE" | "VAR_PCT" | "SPR_PCT" | "NET_TOKEN_FLOW_PCT" | "FLOW_NEUTRAL_PRICE" | "PREMIUM_PCT";
            /**
             * @description Оператор сравнения метрики с порогом, включая пересечение вверх или вниз.
             * @enum {string}
             */
            operator: "GTE" | "LTE" | "CROSSES_ABOVE" | "CROSSES_BELOW";
            /** @description Стабильный идентификатор протокола в нижнем регистре с дефисами. */
            slug: string;
            /** @description Порог в единицах выбранной метрики: доллары для PRICE и FLOW_NEUTRAL_PRICE, проценты для *_PCT, множитель для FDV_REVENUE. */
            threshold: number;
            /**
             * Format: date-time
             * @description UTC-время последнего изменения мутабельной записи, назначенное сервером.
             */
            updatedAt: string;
            /** @description Текст ожидаемого влияния срабатывания триггера на пересмотр вердикта. */
            verdictEffect: string;
        };
        ResearchValuationResponseDto: {
            /**
             * Format: date-time
             * @description UTC-время создания записи, назначенное сервером.
             */
            createdAt: string;
            /** @description Расчётная справедливая полностью разводнённая стоимость в долларах; null — расчёт невозможен. */
            fairFdv: number | null;
            /** @description Цена токена в долларах, при которой чистый токеновый поток равен нулю; null — расчёт невозможен. */
            flowNeutralPrice: number | null;
            /** @description Отношение подразумеваемой выручки к измеренной, выраженное множителем; null — расчёт невозможен. */
            impliedGrowthX: number | null;
            /** @description Годовая выручка в долларах, подразумеваемая текущим FDV и медианой сектора; null — расчёт невозможен. */
            impliedRevenue: number | null;
            /** @description Отклонение текущего FDV от справедливого FDV в процентах; null — расчёт невозможен. */
            premiumPct: number | null;
            /** @description Медианное отношение FDV к годовой выручке среди опубликованных протоколов сектора; null — выборки недостаточно. */
            sectorMedianFdvRevenue: number | null;
            /** @description Число опубликованных протоколов с пригодным FDV/Revenue, вошедших в медиану сектора. */
            sectorSampleSize: number;
            /**
             * Format: date-time
             * @description UTC-время последнего пересчёта оценки, назначенное сервером.
             */
            updatedAt: string;
        };
        ResearchVerdictResponseDto: {
            /** @description Локали, для которых у вердикта сохранён текст. */
            availableLocales: ("RU" | "EN")[];
            /** @description Причина изменения относительно прошлого вердикта; null допустим для первого вердикта. */
            changeReason: string | null;
            /**
             * Format: date-time
             * @description UTC-время создания записи, назначенное сервером.
             */
            createdAt: string;
            /** @description Определяет видимость вердикта в публичных ответах; false означает черновик. */
            isPublished: boolean;
            /** @description Список сработавших блокирующих условий риска; пустой массив означает, что ни одно не сработало. */
            killersFired: ("NEGATIVE_NET_REVENUE" | "NEGATIVE_FLOW_WITH_UNLOCKS" | "NO_VALUE_ACCRUAL" | "UNVERIFIABLE_REVENUE" | "UNILATERAL_TEAM_CONTROL" | "UNRESOLVED_SECURITY_ISSUE" | "INSUFFICIENT_LIQUIDITY" | "HOLDER_CONCENTRATION" | "MISSING_CRITICAL_DATA")[];
            /**
             * Format: date-time
             * @description UTC-время, с которого вердикт считается опубликованным.
             */
            publishedAt: string;
            /** @description Три упорядоченные ссылки на метрики, подтверждающие причины вердикта. */
            reasons: {
                /**
                 * Format: date-time
                 * @description UTC-время создания причины.
                 */
                createdAt?: string;
                /** @description Ссылка на цитируемую метрику. */
                metricRef?: string;
                /** @description Позиция причины от 1 до 3. */
                position?: number;
                /**
                 * Format: date-time
                 * @description UTC-время изменения причины.
                 */
                updatedAt?: string;
            }[];
            /**
             * @description Итоговый уровень риска: LOW, MEDIUM или HIGH. У существующего вердикта уровень задан всегда.
             * @enum {string}
             */
            riskLabel: "LOW" | "MEDIUM" | "HIGH";
            /**
             * Format: date-time
             * @description UTC-время опорного снимка; null означает, что опорный снимок не задан или удалён.
             */
            snapshotTakenAt: string | null;
            /** @description Текст на запрошенной локали; null означает отсутствие перевода без языкового fallback. */
            text: {
                [key: string]: unknown;
            } | null;
            /**
             * Format: date-time
             * @description UTC-время последней правки вердикта, назначенное сервером.
             */
            updatedAt: string;
            /**
             * @description Версия вердикта в формате major.minor. Порядок задаётся разобранными частями, а не строкой: 1.10 новее 1.9.
             * @example 1.0
             */
            version: string;
        };
        UpdateProtocolDto: {
            /** @description Идентификаторы сетей, в которых развёрнут протокол; пустой массив означает, что сети не указаны. */
            chains?: string[];
            /** @description Идентификатор актива в CoinGecko; null означает, что источник не связан. */
            coingeckoId?: string | null;
            /** @description Адреса и метаданные контрактов по сетям в JSON-объекте. */
            contracts?: {
                [key: string]: unknown;
            };
            /** @description Идентификатор протокола в DefiLlama; null означает, что источник не связан. */
            defillamaSlug?: string | null;
            /** @description Определяет видимость протокола в публичных read-ручках. */
            isPublished?: boolean;
            /** @description Отображаемое название протокола для таблиц и страницы разбора. */
            name?: string;
            /**
             * @description Сектор бизнес-модели протокола: LENDING или PERPS.
             * @enum {string}
             */
            sector?: "LENDING" | "PERPS";
            /** @description Биржевой тикер токена без знака валюты. */
            ticker?: string;
        };
        VerdictContentDto: {
            /** @description Три упорядоченные ссылки на разные метрики. */
            reasons: components["schemas"]["ReplaceVerdictReasonDto"][];
            /** @description Локализованные тексты вердикта; требуется хотя бы один, локали не повторяются. */
            texts: components["schemas"]["VerdictTextDto"][];
        };
        VerdictTextDto: {
            /** @description Markdown-текст разбора с валидными плейсхолдерами метрик. */
            body: string;
            /** @description Краткое описание изменения перевода; null, если его нет. */
            changeSummary?: string | null;
            /** @description Непустой Markdown-блок контраргументов. */
            counterarguments: string;
            /**
             * @description Признак машинного перевода текста.
             * @default false
             */
            isMachineTranslated: boolean;
            /**
             * @description Локаль записываемого текста: RU или EN.
             * @enum {string}
             */
            locale: "RU" | "EN";
            /** @description Три локализованных текста причин в порядке позиций 1–3. */
            reasonTexts: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ResearchReadController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description База данных отвечает; latestSnapshotAt показывает время последнего снимка или null, если снимков ещё нет. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "db": "ok",
                     *       "latestSnapshotAt": null,
                     *       "status": "ok",
                     *       "version": "1.0.0"
                     *     }
                     */
                    "application/json": components["schemas"]["ResearchHealthResponseDto"];
                };
            };
            /** @description База данных недоступна; тело ответа помечает API как degraded. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResearchMetricFieldsController_fields: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Полный перечень полей, допустимых в плейсхолдерах прозы вердикта. Публичная ручка: списком не раскрывается ни одно значение, только имена. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchMetricFieldDto"][];
                };
            };
        };
    };
    ResearchWriteController_previewMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewMetricsDto"];
            };
        };
        responses: {
            /** @description Метрики и оценка рассчитаны; ни протокол, ни снимок, ни оценка не записаны. null у отдельных уровней означает, что расчёт невозможен. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchPreviewResponseDto"];
                };
            };
            /** @description Заголовок x-api-key отсутствует или не совпадает ни с одним настроенным ключом. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Запись конфликтует с существующим естественным уникальным ключом. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResearchReadController_protocols: {
        parameters: {
            query?: {
                /** @description Максимальное число протоколов в ответе: от 1 до 200. */
                limit?: number;
                /** @description Число протоколов, пропускаемых от начала выборки; минимум 0. */
                offset?: number;
                /** @description Сектор, которым ограничивается список опубликованных протоколов. */
                sector?: "LENDING" | "PERPS";
                /** @description Включить неопубликованные протоколы; значение true требует действующий x-api-key. */
                includeDrafts?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница протоколов, отсортированная по slug; пустой массив означает, что под условия выборки не подошёл ни один протокол. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "chains": [
                     *           "ethereum"
                     *         ],
                     *         "name": "Aave",
                     *         "sector": "LENDING",
                     *         "slug": "aave",
                     *         "takenAt": null,
                     *         "ticker": "AAVE"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["ResearchProtocolListItemDto"][];
                };
            };
        };
    };
    ResearchWriteController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProtocolDto"];
            };
        };
        responses: {
            /** @description Паспорт создан; тело содержит сохранённую запись с назначенными сервером createdAt и updatedAt. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "chains": [
                     *         "ethereum"
                     *       ],
                     *       "coingeckoId": null,
                     *       "contracts": {
                     *         "ethereum": "0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9"
                     *       },
                     *       "createdAt": "2026-08-18T00:00:00.000Z",
                     *       "defillamaSlug": null,
                     *       "isPublished": false,
                     *       "name": "Aave",
                     *       "sector": "LENDING",
                     *       "slug": "aave",
                     *       "ticker": "AAVE",
                     *       "updatedAt": "2026-08-18T00:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["ResearchProtocolResponseDto"];
                };
            };
            /** @description Заголовок x-api-key отсутствует или не совпадает ни с одним настроенным ключом. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Запись конфликтует с существующим естественным уникальным ключом. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResearchReadController_protocol: {
        parameters: {
            query?: {
                /** @description Локаль текста вердикта; по умолчанию RU. */
                locale?: "RU" | "EN";
            };
            header?: never;
            path: {
                /** @description Стабильный slug опубликованного протокола в нижнем регистре. */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Паспорт с последними опубликованными материалами; null у методики, снимка или вердикта означает, что их ещё нет. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "methodology": null,
                     *       "protocol": {
                     *         "chains": [
                     *           "ethereum"
                     *         ],
                     *         "name": "Aave",
                     *         "sector": "LENDING",
                     *         "slug": "aave",
                     *         "ticker": "AAVE"
                     *       },
                     *       "snapshot": null,
                     *       "triggers": [],
                     *       "verdict": null
                     *     }
                     */
                    "application/json": components["schemas"]["ResearchProtocolPageDto"];
                };
            };
            /** @description Протокол с таким slug не существует или не опубликован. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResearchWriteController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug изменяемого протокола в нижнем регистре. */
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProtocolDto"];
            };
        };
        responses: {
            /** @description Паспорт обновлён; тело содержит запись целиком, включая непереданные поля, сохранившие прежние значения. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "chains": [
                     *         "ethereum"
                     *       ],
                     *       "coingeckoId": "aave",
                     *       "contracts": {
                     *         "ethereum": "0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9"
                     *       },
                     *       "createdAt": "2026-08-18T00:00:00.000Z",
                     *       "defillamaSlug": "aave",
                     *       "isPublished": true,
                     *       "name": "Aave",
                     *       "sector": "LENDING",
                     *       "slug": "aave",
                     *       "ticker": "AAVE",
                     *       "updatedAt": "2026-08-19T09:30:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["ResearchProtocolResponseDto"];
                };
            };
            /** @description Заголовок x-api-key отсутствует или не совпадает ни с одним настроенным ключом. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Протокол с таким slug не существует. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Запись конфликтует с существующим естественным уникальным ключом. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResearchWriteController_deleteProtocol: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug удаляемого протокола. */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Протокол и вся его research-история удалены, оценки соседей по сектору пересчитаны; тело ответа отсутствует. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Заголовок x-api-key отсутствует или не совпадает ни с одним настроенным ключом. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Передан обычный ключ без права удаления протокола. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Протокол с таким slug не существует. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Запись конфликтует с существующим естественным уникальным ключом. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResearchWriteController_methodology: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug протокола, для которого добавляется методика. */
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppendMethodologyDto"];
            };
        };
        responses: {
            /** @description Методика создана со следующим свободным номером редакции; тело содержит сохранённую запись. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "adapterUrl": null,
                     *       "buybackPolicy": null,
                     *       "createdAt": "2026-08-18T00:00:00.000Z",
                     *       "excludedAddresses": [
                     *         "0x0000000000000000000000000000000000000000"
                     *       ],
                     *       "feeStructureSource": null,
                     *       "incentivesSource": null,
                     *       "reserveFactorSource": null,
                     *       "revenueDefinition": "Protocol fees minus token incentives",
                     *       "updatedAt": "2026-08-18T00:00:00.000Z",
                     *       "version": 1,
                     *       "whaleThresholdPct": 5
                     *     }
                     */
                    "application/json": components["schemas"]["ResearchMethodologyResponseDto"];
                };
            };
            /** @description Заголовок x-api-key отсутствует или не совпадает ни с одним настроенным ключом. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Протокол с таким slug не существует. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Запись конфликтует с существующим естественным уникальным ключом. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResearchWriteController_replaceMethodology: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug протокола методики. */
                slug: string;
                /** @description Текущий номер версии методики. */
                version: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceMethodologyDto"];
            };
        };
        responses: {
            /** @description Методика заменена целиком; тело содержит новую редакцию с актуальным номером версии. Непереданные необязательные поля становятся null. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchMethodologyResponseDto"];
                };
            };
            /** @description Заголовок x-api-key отсутствует или не совпадает ни с одним настроенным ключом. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Протокол или версия методики не найдены. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Запись конфликтует с существующим естественным уникальным ключом. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResearchWriteController_deleteMethodology: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug протокола методики. */
                slug: string;
                /** @description Текущий номер версии методики. */
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Методика удалена; тело ответа отсутствует. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Заголовок x-api-key отсутствует или не совпадает ни с одним настроенным ключом. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Протокол или версия методики не найдены. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Запись конфликтует с существующим естественным уникальным ключом. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResearchReadController_snapshots: {
        parameters: {
            query?: {
                /** @description Максимальное число снимков в ответе: от 1 до 200. */
                limit?: number;
                /** @description Число снимков, пропускаемых от начала выборки; минимум 0. */
                offset?: number;
            };
            header?: never;
            path: {
                /** @description Стабильный slug опубликованного протокола в нижнем регистре. */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница снимков от новых к старым; пустой массив означает, что снимков у протокола ещё нет. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example [] */
                    "application/json": components["schemas"]["ResearchSnapshotResponseDto"][];
                };
            };
            /** @description Протокол с таким slug не существует или не опубликован. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResearchWriteController_snapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug протокола, к истории которого добавляется снимок. */
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppendSnapshotDto"];
            };
        };
        responses: {
            /** @description Снимок, метрики и оценка сохранены одной транзакцией; оценки соседей по сектору пересчитаны в ней же. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "price": null,
                     *       "takenAt": "2026-08-18T00:00:00.000Z",
                     *       "valuation": null
                     *     }
                     */
                    "application/json": components["schemas"]["ResearchSnapshotResponseDto"];
                };
            };
            /** @description Заголовок x-api-key отсутствует или не совпадает ни с одним настроенным ключом. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Протокол с таким slug не существует. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Запись конфликтует с существующим естественным уникальным ключом. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResearchWriteController_replaceSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug протокола снимка. */
                slug: string;
                /** @description Текущее UTC-время снимка в ISO 8601. */
                takenAt: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceSnapshotDto"];
            };
        };
        responses: {
            /** @description Снимок заменён целиком, его оценка и оценки соседей по сектору пересчитаны той же транзакцией. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchSnapshotResponseDto"];
                };
            };
            /** @description Заголовок x-api-key отсутствует или не совпадает ни с одним настроенным ключом. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Протокол или снимок не найдены. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Запись конфликтует с существующим естественным уникальным ключом. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResearchWriteController_deleteSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug протокола снимка. */
                slug: string;
                /** @description Текущее UTC-время снимка в ISO 8601. */
                takenAt: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Снимок и его оценка удалены каскадом, сектор пересчитан; тело ответа отсутствует. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Заголовок x-api-key отсутствует или не совпадает ни с одним настроенным ключом. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Протокол или снимок не найдены. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Запись конфликтует с существующим естественным уникальным ключом. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResearchWriteController_triggers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug протокола, набор триггеров которого заменяется. */
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceTriggersDto"];
            };
        };
        responses: {
            /** @description Набор триггеров заменён целиком; тело содержит сохранённый список, пустой массив означает, что триггеров не осталось. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example [] */
                    "application/json": components["schemas"]["ResearchTriggerResponseDto"][];
                };
            };
            /** @description Заголовок x-api-key отсутствует или не совпадает ни с одним настроенным ключом. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Протокол с таким slug не существует. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Запись конфликтует с существующим естественным уникальным ключом. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResearchReadController_verdicts: {
        parameters: {
            query?: {
                /** @description Локаль текста вердикта; по умолчанию RU. */
                locale?: "RU" | "EN";
                /** @description Включить черновики; значение true требует действующий x-api-key. */
                includeDrafts?: boolean;
            };
            header?: never;
            path: {
                /** @description Стабильный slug опубликованного протокола в нижнем регистре. */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description История вердиктов от новых к старым; пустой массив означает, что опубликованных вердиктов ещё нет. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example [] */
                    "application/json": components["schemas"]["ResearchVerdictResponseDto"][];
                };
            };
            /** @description Протокол с таким slug не существует или не опубликован. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResearchWriteController_verdict: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug протокола, для которого публикуется вердикт. */
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppendVerdictDto"];
            };
        };
        responses: {
            /** @description Вердикт создан со следующей версией; без явного isPublished остаётся черновиком и в публичных ответах не виден. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "changeReason": null,
                     *       "killersFired": [],
                     *       "publishedAt": "2026-08-18T00:00:00.000Z",
                     *       "reasons": {},
                     *       "riskLabel": "LOW",
                     *       "version": "1.0"
                     *     }
                     */
                    "application/json": components["schemas"]["ResearchVerdictResponseDto"];
                };
            };
            /** @description Заголовок x-api-key отсутствует или не совпадает ни с одним настроенным ключом. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Протокол с таким slug не существует. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Запись конфликтует с существующим естественным уникальным ключом. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResearchWriteController_replaceVerdict: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug протокола вердикта. */
                slug: string;
                /** @description Текущая версия вердикта. */
                version: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceVerdictDto"];
            };
        };
        responses: {
            /** @description Вердикт заменён целиком; переданный isPublished определяет, публикуется он или возвращается в черновик. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchVerdictResponseDto"];
                };
            };
            /** @description Заголовок x-api-key отсутствует или не совпадает ни с одним настроенным ключом. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Протокол или вердикт не найдены. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Запись конфликтует с существующим естественным уникальным ключом. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResearchWriteController_deleteVerdict: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug протокола вердикта. */
                slug: string;
                /** @description Текущая версия вердикта. */
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Вердикт удалён; текущим становится следующий опубликованный по убыванию версии, тело ответа отсутствует. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Заголовок x-api-key отсутствует или не совпадает ни с одним настроенным ключом. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Протокол или вердикт не найдены. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Запись конфликтует с существующим естественным уникальным ключом. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResearchWriteController_replaceVerdictReasons: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug протокола вердикта. */
                slug: string;
                /** @description Версия вердикта. */
                version: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceVerdictReasonsDto"];
            };
        };
        responses: {
            /** @description Причины заменены целиком; тело ответа отсутствует. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Заголовок x-api-key отсутствует или не совпадает ни с одним настроенным ключом. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Протокол или вердикт не найдены. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Запись конфликтует с существующим естественным уникальным ключом. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResearchWriteController_replaceVerdictText: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug протокола вердикта. */
                slug: string;
                /** @description Версия вердикта. */
                version: string;
                /** @description Локаль текста. */
                locale: "ru" | "en";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceVerdictTextDto"];
            };
        };
        responses: {
            /** @description Текст локали сохранён полной заменой; тело ответа отсутствует. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Заголовок x-api-key отсутствует или не совпадает ни с одним настроенным ключом. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Протокол или вердикт не найдены. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Запись конфликтует с существующим естественным уникальным ключом. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResearchWriteController_deleteVerdictText: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug протокола вердикта. */
                slug: string;
                /** @description Версия вердикта. */
                version: string;
                /** @description Удаляемая локаль текста. */
                locale: "ru" | "en";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Текст указанной локали удалён; тело ответа отсутствует. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Заголовок x-api-key отсутствует или не совпадает ни с одним настроенным ключом. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Протокол, вердикт или перевод не найдены. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Запись конфликтует с существующим естественным уникальным ключом. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResearchReadController_sectorTable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Сектор протоколов, включаемых в сравнительную таблицу. */
                sector: "LENDING" | "PERPS";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Строки сравнительной таблицы сектора; пустой массив означает, что опубликованных данных по сектору нет. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example [] */
                    "application/json": components["schemas"]["ResearchSectorTableRowDto"][];
                };
            };
        };
    };
    ResearchReadController_triggers: {
        parameters: {
            query?: {
                /** @description Slug протокола, триггерами которого ограничивается ответ. */
                slug?: string;
                /** @description Минимальный тариф бота, для которого предназначены триггеры. */
                tier?: "FREE" | "PAID";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Активные публичные триггеры; пустой массив означает, что под фильтр не подошёл ни один триггер. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example [] */
                    "application/json": components["schemas"]["ResearchTriggerResponseDto"][];
                };
            };
        };
    };
}
