"use client";

import { Alert, Button, Checkbox, Divider, FormControlLabel, MenuItem, Paper, Stack, Tab, Tabs, TextField, Tooltip, Typography } from "@mui/material";
import { useCallback, useEffect, useMemo, useState } from "react";

import { metricLabels } from "../../lib/metric-labels";
import { buildVerdictBody, duplicateMetricRefs, mayDeleteTranslation, nextVerdictRequest, renderPreview, unknownPlaceholders, type VerdictFormValues, type VerdictTextValues } from "../../lib/verdict";

interface MetricField { metricRef: string; source: "snapshot" | "valuation"; field: string; placeholder: string }
interface Snapshot extends Record<string, unknown> { takenAt: string; valuation?: Record<string, unknown> | null }
interface Verdict { version: string; riskLabel: VerdictFormValues["riskLabel"]; killersFired: string[]; changeReason: string | null; publishedAt: string | null; isPublished: boolean; snapshotTakenAt: string | null; reasons: { metricRef: string }[]; text: VerdictTextValues | null; availableLocales: string[] }

const blankText = (): VerdictTextValues => ({ body: "", counterarguments: "", reasonTexts: ["", "", ""], changeSummary: "", isMachineTranslated: false });
const blank = (): VerdictFormValues => ({ snapshotTakenAt: "", isPublished: false, riskLabel: "LOW", killersFired: [], changeReason: "", publishedAt: "", metricRefs: ["", "", ""], ru: blankText() });
const request = (method: string, body?: unknown): RequestInit => ({ method, headers: body === undefined ? undefined : { "content-type": "application/json" }, body: body === undefined ? undefined : JSON.stringify(body) });
async function api<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(`/api/admin${path}`, init); const payload = response.status === 204 ? null : await response.json(); if (!response.ok) throw new Error(payload?.message ?? `HTTP ${response.status}`); return payload as T; }
const dateInput = (value: string | null) => value ? new Date(value).toISOString().slice(0, 16) : "";

export function VerdictAdmin({ slug }: { slug: string }) {
  const [values, setValues] = useState<VerdictFormValues>(blank); const [en, setEn] = useState<VerdictTextValues>(blankText);
  const [versions, setVersions] = useState<Verdict[]>([]); const [snapshots, setSnapshots] = useState<Snapshot[]>([]); const [fields, setFields] = useState<MetricField[]>([]);
  const [version, setVersion] = useState<string>(); const [availableLocales, setAvailableLocales] = useState<string[]>([]); const [tab, setTab] = useState<"RU" | "EN">("RU");
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string>();
  const load = useCallback(async () => { try { const [ruVersions, enVersions, nextSnapshots, nextFields] = await Promise.all([
    api<Verdict[]>(`/protocols/${encodeURIComponent(slug)}/verdicts?includeDrafts=true&locale=RU`), api<Verdict[]>(`/protocols/${encodeURIComponent(slug)}/verdicts?includeDrafts=true&locale=EN`),
    api<Snapshot[]>(`/protocols/${encodeURIComponent(slug)}/snapshots`), api<MetricField[]>("/metric-fields"),
  ]); setVersions(ruVersions); setSnapshots(nextSnapshots); setFields(nextFields); if (!version && ruVersions[0]) select(ruVersions[0], enVersions.find((item) => item.version === ruVersions[0].version)); else if (!version && nextSnapshots[0]) setValues((old) => ({ ...old, snapshotTakenAt: nextSnapshots[0].takenAt })); } catch (reason) { setError(reason instanceof Error ? reason.message : "Не удалось загрузить редактор вердикта."); } }, [slug, version]);
  useEffect(() => { void load(); }, [load]);

  function select(item: Verdict, english?: Verdict) { setVersion(item.version); setAvailableLocales(item.availableLocales); setValues({ snapshotTakenAt: item.snapshotTakenAt ?? snapshots[0]?.takenAt ?? "", isPublished: item.isPublished, riskLabel: item.riskLabel, killersFired: item.killersFired, changeReason: item.changeReason ?? "", publishedAt: dateInput(item.publishedAt), metricRefs: item.reasons.map((reason) => reason.metricRef).slice(0, 3) as VerdictFormValues["metricRefs"], ru: item.text ? { ...item.text, changeSummary: item.text.changeSummary ?? "" } : blankText() }); setEn(english?.text ? { ...english.text, changeSummary: english.text.changeSummary ?? "" } : blankText()); }
  const update = <K extends keyof VerdictFormValues>(key: K, value: VerdictFormValues[K]) => setValues((old) => ({ ...old, [key]: value }));
  const placeholders = fields.map((field) => field.placeholder); const activeText = tab === "RU" ? values.ru : en;
  const unknown = useMemo(() => unknownPlaceholders(`${activeText.body}\n${activeText.counterarguments}`, placeholders), [activeText, placeholders]);
  const selectedSnapshot = snapshots.find((item) => item.takenAt === values.snapshotTakenAt); const previewValues = Object.fromEntries(fields.map((field) => [field.placeholder, field.source === "valuation" ? selectedSnapshot?.valuation?.[field.field] : selectedSnapshot?.[field.field]]));
  function updateText(next: VerdictTextValues) { if (tab === "RU") update("ru", next); else setEn({ ...next, isMachineTranslated: false }); }
  async function save() { setBusy(true); setError(undefined); try { const action = nextVerdictRequest(slug, version); const result = await api<Verdict>(action.path, request(action.method, buildVerdictBody(values))); setVersion(result.version); setAvailableLocales(result.availableLocales ?? ["RU"]); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Не удалось сохранить вердикт."); } finally { setBusy(false); } }
  async function saveEn() { if (!version) return setError("Сначала сохраните русскую версию разбора."); setBusy(true); setError(undefined); try { await api(`/protocols/${encodeURIComponent(slug)}/verdicts/${encodeURIComponent(version)}/texts/en`, request("PUT", en)); setAvailableLocales((old) => Array.from(new Set(old.concat("EN")))); } catch (reason) { setError(reason instanceof Error ? reason.message : "Не удалось сохранить перевод."); } finally { setBusy(false); } }
  async function removeEn() { if (!version) return; setBusy(true); try { await api(`/protocols/${encodeURIComponent(slug)}/verdicts/${encodeURIComponent(version)}/texts/en`, { method: "DELETE" }); setEn(blankText()); setAvailableLocales((old) => old.filter((item) => item !== "EN")); } catch (reason) { setError(reason instanceof Error ? reason.message : "Не удалось удалить перевод."); } finally { setBusy(false); } }
  function newVersion() { setVersion(undefined); update("ru", { ...values.ru, changeSummary: "" }); setEn(blankText()); setAvailableLocales([]); }

  return <><Divider sx={{ my: 4 }} /><Stack spacing={2}>
    <Typography variant="h5">Вердикт, причины и проза</Typography>{error ? <Alert severity="error">{error}</Alert> : null}
    <Stack direction="row" spacing={1} flexWrap="wrap">{versions.map((item) => <Button key={item.version} variant={version === item.version ? "contained" : "outlined"} onClick={() => select(item)}>{item.version}{item.isPublished ? " · опубликован" : " · черновик"}</Button>)}<Button onClick={newVersion}>Новая версия разбора</Button></Stack>
    <Paper sx={{ p: 2 }}><Stack spacing={2}><Typography variant="h6">Суждение {version ? `v${version}` : "— новая версия"}</Typography>
      <TextField required select label="Опорный снимок" value={values.snapshotTakenAt} onChange={(event) => update("snapshotTakenAt", event.target.value)}>{snapshots.map((item) => <MenuItem value={item.takenAt} key={item.takenAt}>{new Intl.DateTimeFormat("ru", { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.takenAt))}</MenuItem>)}</TextField>
      <TextField select label="Риск" value={values.riskLabel} onChange={(event) => update("riskLabel", event.target.value as VerdictFormValues["riskLabel"])}>{["LOW", "MEDIUM", "HIGH"].map((item) => <MenuItem key={item} value={item}>{item}</MenuItem>)}</TextField>
      <TextField label="Сработавшие убийцы (через запятую)" helperText={values.killersFired.length && values.riskLabel !== "HIGH" ? "Непустой список убийц допускается только для HIGH — сервер проверит это при сохранении." : ""} value={values.killersFired.join(", ")} onChange={(event) => update("killersFired", event.target.value.split(",").map((item) => item.trim()).filter(Boolean))} />
      <TextField label="Причина изменения суждения" value={values.changeReason} onChange={(event) => update("changeReason", event.target.value)} /><TextField type="datetime-local" InputLabelProps={{ shrink: true }} label="Дата публикации" value={values.publishedAt} onChange={(event) => update("publishedAt", event.target.value)} />
      <FormControlLabel control={<Checkbox checked={values.isPublished} onChange={(event) => update("isPublished", event.target.checked)} />} label="Опубликовать" />
    </Stack></Paper>
    <Tabs value={tab} onChange={(_, value: "RU" | "EN") => setTab(value)}><Tab label="RU" value="RU" /><Tab label={`EN · ${availableLocales.includes("EN") ? en.isMachineTranslated ? "машинный" : "выверено" : "нет перевода"}`} value="EN" /></Tabs>
    <Paper sx={{ p: 2 }}><Stack spacing={2}><Typography variant="h6">Три причины</Typography>{values.metricRefs.map((metricRef, index) => <Stack key={index} direction={{ xs: "column", md: "row" }} spacing={1} draggable onDragStart={(event) => event.dataTransfer.setData("text/plain", String(index))} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { const from = Number(event.dataTransfer.getData("text/plain")); const refs = [...values.metricRefs]; const texts = [...activeText.reasonTexts]; [refs[index], refs[from]] = [refs[from], refs[index]]; [texts[index], texts[from]] = [texts[from], texts[index]]; update("metricRefs", refs as VerdictFormValues["metricRefs"]); updateText({ ...activeText, reasonTexts: texts as VerdictTextValues["reasonTexts"] }); }}>
      <TextField select label={`Метрика ${index + 1}`} value={metricRef} error={duplicateMetricRefs(values.metricRefs).includes(metricRef)} onChange={(event) => { const refs = [...values.metricRefs]; refs[index] = event.target.value; update("metricRefs", refs as VerdictFormValues["metricRefs"]); }} sx={{ minWidth: 280 }}>{fields.map((field) => <MenuItem key={field.metricRef} value={field.metricRef}>{metricLabels[field.metricRef as keyof typeof metricLabels]?.[tab.toLowerCase() as "ru" | "en"] ?? field.metricRef}</MenuItem>)}</TextField>
      <TextField fullWidth label={`Текст причины ${index + 1}`} value={activeText.reasonTexts[index]} onChange={(event) => { const texts = [...activeText.reasonTexts]; texts[index] = event.target.value; updateText({ ...activeText, reasonTexts: texts as VerdictTextValues["reasonTexts"] }); }} /></Stack>)}</Stack></Paper>
    <Stack direction={{ xs: "column", md: "row" }} spacing={2}><Stack flex={1} spacing={2}><Stack direction="row" flexWrap="wrap" gap={1}>{fields.map((field) => <Button size="small" key={field.placeholder} onClick={() => updateText({ ...activeText, body: `${activeText.body}{{${field.placeholder}}}` })}>{field.placeholder}</Button>)}</Stack>
      {unknown.length ? <Alert severity="error">Неизвестные плейсхолдеры: {unknown.join(", ")}</Alert> : null}<TextField multiline minRows={8} label="Текст (Markdown)" value={activeText.body} onChange={(event) => updateText({ ...activeText, body: event.target.value })} /><TextField multiline minRows={3} label="Контраргументы" value={activeText.counterarguments} onChange={(event) => updateText({ ...activeText, counterarguments: event.target.value })} /><TextField required={!version && versions.length > 0} label="Описание изменений" value={activeText.changeSummary} onChange={(event) => updateText({ ...activeText, changeSummary: event.target.value })} />
      {tab === "EN" ? <FormControlLabel control={<Checkbox checked={en.isMachineTranslated} onChange={(event) => setEn((old) => ({ ...old, isMachineTranslated: event.target.checked }))} />} label="Машинный перевод" /> : null}</Stack>
      <Paper sx={{ p: 2, flex: 1, whiteSpace: "pre-wrap" }}><Typography variant="h6">Превью</Typography><Typography>{renderPreview(activeText.body, previewValues)}</Typography><Divider sx={{ my: 2 }} /><Typography>{renderPreview(activeText.counterarguments, previewValues)}</Typography></Paper></Stack>
    <Stack direction="row" spacing={1}><Button disabled={busy || unknown.length > 0 || (!version && versions.length > 0 && !values.ru.changeSummary.trim())} variant="contained" onClick={() => void (tab === "RU" ? save() : saveEn())}>{busy ? "Сохранение…" : tab === "RU" ? version ? "Сохранить вердикт" : "Создать версию" : "Сохранить EN"}</Button>{tab === "EN" ? <Tooltip title={!mayDeleteTranslation(values.isPublished, availableLocales) ? "Сначала верните опубликованный вердикт в черновик." : ""}><span><Button color="error" disabled={busy || !availableLocales.includes("EN") || !mayDeleteTranslation(values.isPublished, availableLocales)} onClick={() => void removeEn()}>Удалить перевод</Button></span></Tooltip> : null}</Stack>
  </Stack></>;
}
